#!/usr/bin/python3
import sys
import psycopg2


conn = None
if len(sys.argv) < 3:
    print("Usage: ./courses-studied studentID term")
    exit(1)
studentId = sys.argv[1]
term = sys.argv[2]

"""
People(id, family, given, fullname, birthday, origin)

Students(id)

Subjects(id, code, name, uoc, offeredby, ...)
Courses(id, subject, term, homepage)
Streams(id, code, name, offeredby, stype, ...)
Programs(id, code, name, uoc, offeredby, ...)

Terms(id, year, ttype, code, name, starting, ending)

Course_enrolments(student, course, mark, grade)
Stream_enrolments(part_of_prog_enr, stream)
Program_enrolments(id, student, term, program, ...)

OrgUnits(id, utype, name, longname, unswid)
OrgUnit_Types(id, name)

"""

student_query = """
select id
from Students
where id = %s
"""

# In this query, select subjects that given studentId is taking at given term
subject_query = """
select s.code, s.name
from Subjects s
join Courses c on s.id = c.subject
join Terms t on c.term = t.id
join Course_enrolments ce on c.id = ce.course
join Students stu on ce.student = stu.id
where stu.id = %s
and t.code = %s
"""
try:
    conn = psycopg2.connect(f"dbname=uni")
    cur = conn.cursor()

    cur.execute(student_query, [studentId])
    res = cur.fetchone()
    if res is None:
        print("No such student")
        exit(0)

except psycopg2.Error as err:
    print("database error: ", err)
finally:
    if conn is not None:
        conn.close()
